
import os

file_path = "/home/javiercruces/github/sentinel/content/posts/cortafuegos/fortinet_dos/fortinet_dos.md"

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = [
    ("Vamos a comprobar que desde la DMZ podemos hacer el ping a Odin :", "Vamos a comprobar que desde la DMZ podemos hacer el ping a Odin:"),
    ("Como vemos la regla esta funcionando , así que vamos a comprobar los hits :", "Como vemos, la regla está funcionando, así que comprobaremos los hits:"),
    (" la red LAN no podemos limitar el ping hacia Odin ya que no pasa por el cortafuegos si no por el switch .", " la red LAN no podemos limitar el ping hacia Odin, ya que no pasa por el cortafuegos, sino por el switch."),
    ("Algo parecido ocurrirá desde la WAN , al ser un ping dirigido a la IP de la interfaz este se desactiva desde la configuración de la misma , siempre se rechaza de manera silenciosa pero no da opción a elegirlo  :", "Algo parecido ocurrirá desde la WAN; al ser un ping dirigido a la IP de la interfaz, este se desactiva desde la configuración de la misma, y siempre se rechaza de manera silenciosa, sin dar opción a elegir el método:"),
    (" La máquina Odin puede hacer ping a la LAN, la DMZ y al exterior. ", "### La máquina Odin puede hacer ping a la LAN, la DMZ y al exterior.\n\n"),
    (" La maquina Odin por la propia topologia puede hacerle ping a todas las maquinas de la LAN ya que el trafico hacia esta red pasa por el swicht .", "La máquina Odin, por la propia topología, puede hacer ping a todas las máquinas de la LAN, ya que el tráfico hacia esta red pasa por el switch."),
    ("Para que pueda hacer ping hacia la  DMZ y a la WAN vamos a crear dos reglas :", "Para que pueda hacer ping hacia la DMZ y la WAN, crearemos dos reglas:"),
    (" la regla para la WAN :", "La regla para la WAN:"),
    (" la regla para la DMZ :", "La regla para la DMZ:"),
    (" Vamos a comprobar los hits de las dos reglas que acabamos de crear :", "Vamos a comprobar los hits de las dos reglas que acabamos de crear:"),
    (" Desde la máquina Hela se puede hacer ping y conexión ssh a las máquinas de la LAN. ", "### Desde la máquina Hela se puede hacer ping y conexión SSH a las máquinas de la LAN.\n\n"),
    (" Para lograr esto creare la siguiente regla . Podríamos separarla en 2 reglas independientes para tener los contadores por separado , pero en este caso no es importante distinguir el trafico .", "Para lograr esto, crearé la siguiente regla. Podríamos separarla en dos reglas independientes para tener los contadores por separado, pero en este caso no es importante distinguir el tráfico."),
    (" Vamos a comprobar la regla , haciendo un ping a las distintas maquinas de la red LAN , ya que anteriormente había una regla para permitir todos los pings hacia Odin :", "Vamos a comprobar la regla haciendo un ping a las distintas máquinas de la red LAN, ya que anteriormente había una regla para permitir todos los pings hacia Odin:"),
    (" Ahora comprobaremos que podemos conectarnos por ssh desde Hela a la LAN :", "Ahora comprobaremos que podemos conectarnos por SSH desde Hela a la LAN:"),
    (" La regla funciona correctamente , vamos a comprobar que ha subido los hits :", "La regla funciona correctamente; comprobemos que han subido los hits:"),
    (" Desde cualquier máquina de la LAN se puede conectar por ssh a la máquina Hela. ", "### Desde cualquier máquina de la LAN se puede conectar por SSH a la máquina Hela.\n\n"),
    (" Para ello vamos a crear la siguiente regla :", "Para ello, vamos a crear la siguiente regla:"),
    (" Ahora comprobaremos la regla :", "Ahora comprobaremos la regla:"),
    (" Comprobemos que los hits de la regla han subido :", "Comprobemos que los hits de la regla han subido:"),
    (" Configurar la máquina Odin para que las máquinas de LAN y DMZ puedan acceder al exterior. ", "### Configurar la máquina Odin para que las máquinas de la LAN y DMZ puedan acceder al exterior.\n\n"),
    (" El SNAT en este dispositivo podemos elegir activarlo por cada regla y no en general . Si te has fijado a lo largo de la practica en todas las reglas que implica dar un salto de interfaz he marcado la casilla NAT :", "El SNAT en este dispositivo se puede activar por cada regla, en lugar de hacerlo de forma general. Si te has fijado, a lo largo de la práctica, en todas las reglas que implican un salto de interfaz, he marcado la casilla NAT:"),
    (" Por lo que este apartado se va a ir realizando a lo largo de la practica conforme creemos las reglas .", "Por lo tanto, este apartado se irá realizando a lo largo de la práctica conforme creemos las reglas."),
    (" Las máquinas de la LAN pueden hacer ping al exterior y navegar. ", "### Las máquinas de la LAN pueden hacer ping al exterior y navegar.\n\n"),
    (" Vamos a tener que crear 3 reglas :", "Para ello, tendremos que crear tres reglas:"),
    (" De estas tres reglas las dos primeras están creadas con anterioridad :", "De estas tres reglas, las dos primeras ya están creadas:"),
    (" Por lo que solo nos queda añadir la regla del ping , que seria la siguiente :", "Por lo que solo nos queda añadir la regla del ping, que sería la siguiente:"),
    (" Comprobemos las reglas , desde un cliente de la red LAN:", "Comprobemos las reglas desde un cliente de la red LAN:"),
    (" Así quedarían nuestras tres reglas , veremos que tenemos hits en las mismas  :", "Así quedarían nuestras tres reglas; veremos que tenemos hits en todas ellas:"),
    (" La máquina Hela puede navegar. Instala un servidor web, un servidor ftp y un servidor de correos si no los tienes aún. ", "### La máquina Hela puede navegar. Instala un servidor web, un servidor FTP y un servidor de correos si no los tienes aún.\n\n"),
    (" Para realizar esto es necesario tener permitido el DNS y la navegación . Para ello he creado la siguiente regla :", "Para realizar esto, es necesario permitir el DNS y la navegación. Para ello, he creado la siguiente regla:"),
    (" La he creado en una sola regla para ahorrar en el numero de las mismas , he borrado las que permitía el ping desde DMZ a LAN de ejercicios anteriores .", "La he creado en una sola regla para ahorrar espacio; he borrado las reglas que permitían el ping desde la DMZ a la LAN de ejercicios anteriores."),
    (" Configura la máquina Odin para que los servicios web y ftp sean accesibles desde el exterior. ", "### Configura la máquina Odin para que los servicios web y FTP sean accesibles desde el exterior.\n\n"),
    (" Para hacer el DNAT deberemos de crear 2 IPs virtuales , como hicimos en cortafuegos I .", "Para hacer el DNAT, deberemos crear dos IPs virtuales, como hicimos en Cortafuegos I."),
    (" Una para cada servicio que queramos hacer un DNAT . Para el servidor web :", "Una para cada servicio que queramos hacer DNAT. Para el servidor web:"),
    (" Y para el servidor FTP :", "Y para el servidor FTP:"),
    (" Ahora vamos a crear la propia regla de DNAT para el servidor web , en la cual como destino indicamos la IP virtual que acabamos de crear :", "Ahora crearemos la regla de DNAT para el servidor web, en la cual, como destino, indicamos la IP virtual que acabamos de crear:"),
    (" Veremos que si accedemos a la IP del cortafuegos de la WAN accederemos al apache de Hela :", "Veremos que, si accedemos a la IP del cortafuegos desde la WAN, accederemos al Apache de Hela:"),
    (" También crearemos la regla DNAT para el servidor FTP :", "También crearemos la regla DNAT para el servidor FTP:"),
    (" Vamos a comprobar el acceso al servidor ftp :", "Vamos a comprobar el acceso al servidor FTP:"),
    (" Si comprobamos los hits de las reglas veremos que en ambas ha subido :", "Si comprobamos los hits de las reglas, veremos que en ambas han subido:"),
    (" El servidor web y el servidor ftp deben ser accesibles desde la LAN y desde el exterior. ", "### El servidor web y el servidor FTP deben ser accesibles desde la LAN y desde el exterior.\n\n"),
    (" Para realizar este ejercicio deberemos de volver a generar las 2 IPs virtuales pero ahora indicaremos la IP de la tarjeta LAN del firewall .", "Para realizar este ejercicio, deberemos generar nuevamente las dos IPs virtuales, pero ahora indicaremos la IP de la interfaz LAN del firewall."),
    (" Para el DNAT del servidor web :", "Para el DNAT del servidor web:"),
    (" Repetiremos lo mismo para el servicio FTP , cambiando el servicio :", "Repetiremos lo mismo para el servicio FTP, cambiando el servicio:"),
    (" Ahora crearemos las 2 reglas de DNAT para permitir el acceso desde la LAN .", "Ahora crearemos las dos reglas de DNAT para permitir el acceso desde la LAN."),
    (" Para el servidor web :", "Para el servidor web:"),
    (" Para el servidor FTP:", "Para el servidor FTP:"),
    (" Vamos a comprobar que podemos acceder a ambos servicios :", "Vamos a comprobar que podemos acceder a ambos servicios:"),
    (" Comprobemos que han subido los hits en las reglas :", "Comprobemos que han subido los hits en las reglas:"),
    (" El servidor de correos sólo debe ser accesible desde la LAN. ", "### El servidor de correos sólo debe ser accesible desde la LAN.\n\n"),
    (" Volvemos a repetir los mismos pasos , le crearemos una IP virtual para poder hacer la regla de DNAT :", "Volvemos a repetir los mismos pasos; crearemos una IP virtual para poder realizar la regla de DNAT:"),
    (" Ahora vamos a crear la regla de DNAT :", "Ahora crearemos la regla de DNAT:"),
    (" Y comprobaremos que desde un PC de la LAN haciendo un telnet llegamos al servidor de correos :", "Y comprobaremos que, desde un PC de la LAN, haciendo un telnet, llegamos al servidor de correos:"),
    (" Veremos que el hit de la regla ha subido :", "Veremos que el hit de la regla ha subido:"),
    (" En la máquina Loki instala un servidor Postgres si no lo tiene aún. A este servidor se puede acceder desde la DMZ, pero no desde el exterior. ", "### En la máquina Loki instala un servidor Postgres si no lo tiene aún. A este servidor se puede acceder desde la DMZ, pero no desde el exterior.\n\n"),
    (" Volveremos a repetir el proceso de crear una nueva IP virtual para este servicio . Ademas en este caso he tenido que crear el servicio ya que no existía .", "Volveremos a repetir el proceso de crear una nueva IP virtual para este servicio. Además, en este caso, he tenido que crear el servicio ya que no existía."),
    (" Vamos a crear la regla de DNAT :", "Vamos a crear la regla de DNAT:"),
    (" Vamos a comprobar que tenemos acceso al servidor pgsql desde la red DMZ :", "Vamos a comprobar que tenemos acceso al servidor pgsql desde la red DMZ:"),
    (" Comprobaremos que la regla tiene hits :", "Comprobaremos que la regla tiene hits:"),
    (" Evita ataques DoS por ICMP Flood, limitando a 4 el número de peticiones por segundo desde una misma IP. ", "### Evita ataques DoS por ICMP Flood, limitando a 4 el número de peticiones por segundo desde una misma IP.\n\n"),
    (" Dentro del apartado de políticas y objetos , encontramos un apartado para crear políticas para DoS . En mi caso he creado una con los valores recomendados que da el fabricante . Y he cambiado el limite de ICMP Flood a 4 paquetes por segundo .", "Dentro del apartado de políticas y objetos, encontramos una sección para crear políticas contra DoS. En mi caso, he creado una con los valores recomendados por el fabricante y he limitado el ICMP Flood a 4 paquetes por segundo."),
    (" Vamos a comprobar que nos bloquea el trafico si excedemos ese limite . Con este comando estamos enviando 3 paquetes por segundo que es inferior al limite establecido asi que no cortara ningún paquete :", "Vamos a comprobar que nos bloquea el tráfico si excedemos ese límite. Con este comando enviamos 3 paquetes por segundo, que es inferior al límite establecido, por lo que no cortará ningún paquete:"),
    (" Si aumentamos los de paquetes por segundos , bloqueara todos los paquetes que superen a 4 por segundo , por eso deja pasar los 4 primeros de cada segundo :", "Si aumentamos el número de paquetes por segundo, bloqueará todos los paquetes que superen los 4 por segundo; por eso deja pasar los 4 primeros de cada segundo:"),
    (" El cortafuegos ha registrado como una anomalía el trafico que ha tirano :", "El cortafuegos ha registrado como una anomalía el tráfico que ha descartado:"),
    (" Evita ataques DoS por SYN Flood. ", "### Evita ataques DoS por SYN Flood.\n\n"),
    (" Con el filtro que hemos activado en el ejercicio anterior tenemos limitada las peticiones TCP a 2000 por minuto desde la misma IP para evitar este tipo de ataque . Vemos que el filtro elimina las peticiones maliciosas y no deja que el ataque tenga efecto :", "Con el filtro que hemos activado en el ejercicio anterior, tenemos limitada las peticiones TCP a 2000 por minuto desde la misma IP para evitar este tipo de ataque. Vemos que el filtro elimina las peticiones maliciosas y no deja que el ataque tenga efecto:"),
    (" Evita que realicen escaneos de puertos a Odin. ", "### Evita que realicen escaneos de puertos a Odin.\n\n"),
    (" En lugar de hacerlo a Odin por la propia topologia vamos a hacerlo para evitar escaneos desde la WAN .", "En lugar de hacerlo a Odin por la propia topología, vamos a hacerlo para evitar escaneos desde la WAN."),
    (" Para ello nos abrimos una terminal y lo que vamos a hacer es crear una firma de IPS para evitar los paquetes con una determinada bandera que usa un escaneo determinado . En este caso vamos a evitar el escaneo de NMAP XMAS .", "Para ello, abriremos una terminal y crearemos una firma de IPS para evitar los paquetes con una determinada bandera que usa un escaneo determinado. En este caso, evitaremos el escaneo de NMAP XMAS."),
    (" Una vez configurado nos aparecera la regla que hemos creado en IPs signatures :", "Una vez configurado, nos aparecerá la regla que hemos creado en IPs signatures:"),
    (" Ahora vamos a crear una regla IPS para asociarla con esta politica de firmas :", "Ahora vamos a crear una regla IPS para asociarla con esta política de firmas:"),
    (" Añadiremos en IPS signatures and filters , el nuevo filtro que hemos creado anteriormente :", "Añadiremos en IPS signatures and filters el nuevo filtro que hemos creado anteriormente:"),
    (" A continuación en las reglas de DNAT donde queramos controlar que no sepan que puertos tenemos abiertos , asignaremos la nueva política IPS :", "A continuación, en las reglas de DNAT donde queramos controlar que no sepan qué puertos tenemos abiertos, asignaremos la nueva política IPS:"),
    (" En mi caso vamos a probarlo para la regla DNAT de ssh :", "En mi caso, lo probaremos para la regla DNAT de SSH:"),
    (" Si lanzo el NMAP desde mi host que esta en la red WAN , vemos que el puerto 2222 que es el que esta regla tiene abierto no lo detecta :", "Si lanzo NMAP desde mi host en la red WAN, vemos que no detecta el puerto 2222, que es el que esta regla tiene abierto:"),
    (" Y el propio cortafuegos nos avisara de que ha habido un escaneo de puertos que ha bloqueado , para ver esto dirígete a Log & Report > Intrusion prevention :", "Y el propio cortafuegos nos avisará de que ha habido un escaneo de puertos bloqueado; para ver esto, dirígete a Log & Report > Intrusion prevention:"),
]

for old, new in replacements:
    content = content.replace(old, new)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)
